"""Core graph primitives."""

from .builder import GraphBuilder
from .edge import Edge, EdgePredicate, ToolSchemaProvider
from .graph import (
    GRAPH_STATE_SCHEMA,
    CompletedNode,
    Graph,
    GraphRunResult,
    GraphRunStatus,
    NodeActivation,
    NodeState,
)
from .message import (
    MESSAGE_HISTORY_SCHEMA,
    ContentBlock,
    ContentBlockKind,
    FileBlock,
    Message,
    MessageRole,
    ReasoningBlock,
    TextBlock,
    ToolCallBlock,
    ToolResultBlock,
    content_block_from_dict,
    content_block_to_dict,
    message_from_dict,
    message_history_from_dict,
    message_history_to_dict,
    message_to_dict,
    messages_from_dict,
    messages_to_dict,
)
from .node import (
    Node,
    NodeKind,
    NodeResult,
    UpstreamOutputs,
    merge_messages,
)

__all__ = [
    "CompletedNode",
    "ContentBlock",
    "ContentBlockKind",
    "Edge",
    "EdgePredicate",
    "FileBlock",
    "GRAPH_STATE_SCHEMA",
    "Graph",
    "GraphBuilder",
    "GraphRunResult",
    "GraphRunStatus",
    "MESSAGE_HISTORY_SCHEMA",
    "Message",
    "MessageRole",
    "Node",
    "NodeActivation",
    "NodeKind",
    "NodeResult",
    "NodeState",
    "ReasoningBlock",
    "TextBlock",
    "ToolCallBlock",
    "ToolResultBlock",
    "ToolSchemaProvider",
    "UpstreamOutputs",
    "content_block_from_dict",
    "content_block_to_dict",
    "merge_messages",
    "message_from_dict",
    "message_history_from_dict",
    "message_history_to_dict",
    "message_to_dict",
    "messages_from_dict",
    "messages_to_dict",
]
